sudo: required # Run in a container
services:
- docker # Allow running docker commands

env:
  global:
  - BRANCH=$TRAVIS_BRANCH

script: make build

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - make push
