sudo: false # Run in a container
services:
- docker # Allow running docker commands

env:
  global:
  - BRANCH=$TRAVIS_BRANCH
  #DOCKER_EMAIL
  - secure: ofhBHM5dgink26clkEf2QfJqBj58BJqun2lSoXXU24gYpryLTK6COM0ETvbIzhyR6i3Y43RHOUbLrzX1SrKdF8d9q7WPw16tvbNpkbwX4cfUm2iIqO8VpRT/iPdZ8MGukFqydzy97NrhSknYHoIwZZf38nd9DBKVsCJrzTVXiJ/U45r3Qz0T9RgUXD1uudKZIfoKQqZjaBEeU0GotV+FqkiaKMTlXGv3B4ZxftxycSBV4mjyXEFlrdzb0J4UvlbLfYw3m3yiSn15mGYvNVUURXSzLwgwp9No6xn2/lM0LPy2Xo+OpsruoHIapXaRkUPIDgc8FVWtXPamNvmAhF+8NxnCsC0vlPrBU6xJyI7m80YsCFuKftidqt0+i9e2ZaQIE/N6Cnp6J8fUVZUhcHa+NSs51BtF3VCkvBtZPQ/BJW0wavi3PwzBmZNHT+IJ0DPXCK7RM1zQAQrDGkdB2knRfebouDcgAf++GjiV+sJyhlFvsWys0xFrdZJpuqSZUmbBELjSkgxtEMGsJTU25Y1F+JR//ZnsrFoTIXd5s3D0RbS9qtODsjwgPb82Ssis1WH03hoZyWv/AkW1w/crDzDtrc9C7f3i9MJhytHboRxFS8couDp9io30ECpKCIvXyJ3tjFHCpolzSVIA54ZfcKigg3Q1lZ4xW2zHBUCxOCqKd4I=
  #DOCKER_USER
  - secure: aV+4m31PBIR+V5MZofHhC0/4oI56+OSdEFiZvYjQ7p13wdcVzANx40S+flo8kvFymN2yx1shxGBNksRyspibD43EaZjP3QgLrBBLjY+lMGMn+GysKR0ZZZRPT8PZpHikmUCUxKoD6QWWxeYiwVl2bFIlENGCqN0OW8sydZy1GeC20px4qVxJ4AlA/j5QBpu+pk4J6xgsFFb1gRS4VUoUYYiEEmicUa2OHCQ/PJp55TEhXA4s+LkgNxjDHwFVGBrpC7n/nq+1e/ycl8M3AT8N97TRy6KXgcYgJ/7EQ8wA/jCtbP51TgmPWRyLG/XQ2ie0kdpY7cht16DxJxnUDfuXT7VGjy9fT056UA+m8fa/inB2+vtIkLcabTxAMrEMkbsUPu5HQBR1rQg0l0EcSayv0gskLPay3Ad8O21+Rt6TMRKUsksrcvq7aq5f0emrcKn/G9FANAn5aS3uO0rbj9Ctim9gofxOTQaLoErGD0kmvMRWHjEv+KQnGCCG4yPxqSnkI2aevcY5eAIRGfWLEFO6ycQvhqnm956WRMHi6MTJoQGhdBuIjTsXnQrz+L9HRE0syqi921sYKQA1OHeZjAQhIfG2yssjmdo1p/QMZjTmDrTgljovAZ4CSOtAS7chb1PGFyiEwS6xvXmpEcxY8wO3QgI5do3J7aBT5uK8rmD6PEs=
  #DOCKER_PASSWORD
  - secure: qM05RU2Zl/iK78jZMwct4QjDPlcYWzO1euUjpKgQIlXOVzKCKLD3CURA10q52ChkDYsK+tHMy0GtUxNg3LviX9cp9RrRm2Z7CCplwiMvAGT2GLPG7dtKItsBwAQ5dcgTales8KoVcY6CIvLnn5B5w9LjWmB0MMHbvSd56aWVmcT2Rz/i0JFw43fZuEWkkVfSYYe8AGIlTgtzt2KHIgvUm0i9aw/usJUV4TmWt1uFuRGn/DIhk9wieaa9KDY3UmivDrdPvPSvHbHW+9DAEku2KK/PKrm1hxxMDsheqa0ybZLcEzwGqxlm6GdbZ8ZKM2RYdCyyIk4cnojodkSR+9BiV3oqsQXz+Gcy3JVNa1NwajfgtFHXfASv15JKYfPo/D2xPcVRX226DhoJFYeFRAvgWfMoWgWY1heSG3MMcFouVugaleqEd8K45mYS+1GCaU6/pLPNafIZVDKjuqL+ypJEVmWMfDTUXi+p4om2R/lH7ia0dHSb+IyB5cTo+SQlach53ok2Lcu65xtUhgzS/77Fz+5tzGqyh4HQOqSL3MjSsu3CCB/bB/C53oSEkrMCaSmFOUD8UgzgAJLIo9d6KmNON1KziOA4TgOicwWA85B6dH0t1Wo+022OYjIcMC6uS+W5C7vmkrG9VdlKMdLiDd76CiGArNsNOBg0TOluBzE3rCo=

script: make build

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - make push
